export const SPOTIFY_ERRORS = {
	NO_TOKEN: 'NO_SPOTIFY_TOKEN',
	REVOKED: 'SPOTIFY_REVOKED',
	EXPIRED: 'SPOTIFY_TOKEN_EXPIRED',
	RECONNECT_NEEDED: 'SPOTIFY_RECONNECT_NEEDED',
	ACCESS_ERROR: 'SPOTIFY_ACCESS_ERROR',
} as const;

export const SPOTIFY_API_BASE = 'https://api.spotify.com/v1';

export const SPOTIFY_PROVIDER_ID = 'spotify';
