// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
	"sidebar": {
		"routes": {
			"overview": "Overview",
			"listeningHistory": "Listening History",
			"moodAnalysis": "Mood Analysis",
			"insights": "Insights",
			"recentPlays": "Recent Plays",
			"profile": "Profile"
		},
		"userMenu": {
			"myAccount": "My Account",
			"profile": "Profile",
			"logout": "Logout"
		},
		"toggleMenu": "Toggle menu",
		"backToHome": "Back to Home"
	},
	"pages": {
		"overview": {
			"greeting": {
				"morning": "Good morning, {name}",
				"afternoon": "Good afternoon, {name}",
				"evening": "Good evening, {name}",
				"default": "Welcome back, {name}"
			},
			"subtitle": "Here's what you've been listening to recently",
			"stats": {
				"totalHours": "Total Hours",
				"totalPlays": "Total Plays",
				"uniqueArtists": "Unique Artists",
				"uniqueTracks": "Unique Tracks",
				"hoursSuffix": "h"
			},
			"charts": {
				"weeklyActivity": "Weekly Activity"
			},
			"mediaList": {
				"topTracks": "Top Tracks",
				"topArtists": "Top Artists",
				"noTracks": "No tracks to display",
				"noArtists": "No artists to display"
			}
		},
		"listening": {
			"subtitle": "Your audio journey <highlight>{period}</highlight>",
			"periodLastYear": "over the last year",
			"periodYear": "in {year}",
			"calendar": {
				"tooltipTracks": "{count, plural, one {# track} other {# tracks}}",
				"less": "Less",
				"more": "More",
				"total": "{{count}} activities in {{year}}",
				"totalLastYear": "{{count}} activities over the last year"
			},
			"charts": {
				"title": "Hourly Activity",
				"description": "Activity distribution by time of day"
			}
		}
	},
	"shared": {
		"filters": {
			"day": "Day",
			"week": "Week",
			"month": "Month",
			"lastYear": "Last year",
			"top": "Top {count}"
		}
	},
	"apiErrors": {
		"defaultTitle": "Something went wrong",
		"defaultMessage": "An unknown error occurred.",
		"unauthorized": "Your session has expired. Please refresh the page or log in again.",
		"serverError": "Failed to fetch dashboard data. Please try again later.",
		"retryButton": "Try Again"
	}
};
export default messages;